//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FESOVSE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FESOVSE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;character id =&quot;CDE7C2253782C205&quot; name=&quot;Alm&quot;&gt;
        ///    &lt;text displayName =&quot;Alm&quot;/&gt;
        ///    &lt;base hp=&quot;28&quot; atk=&quot;10&quot; skl=&quot;7&quot; spd=&quot;6&quot; lck=&quot;7&quot; def=&quot;5&quot; res=&quot;4&quot;/&gt;
        ///    &lt;max hp=&quot;52&quot; atk=&quot;41&quot; skl=&quot;41&quot; spd=&quot;39&quot; lck=&quot;39&quot; def=&quot;41&quot; res=&quot;40&quot;/&gt;
        ///  &lt;/character&gt;
        ///  &lt;character id =&quot;07EF94FDE3950E05&quot; name=&quot;Lukas&quot;&gt;
        ///    &lt;text displayName =&quot;Lukas&quot;/&gt;
        ///    &lt;base hp=&quot;22&quot; atk=&quot;10&quot; skl=&quot;4&quot; spd=&quot;4&quot; lck=&quot;2&quot; def=&quot;5&quot; res=&quot;2&quot;/&gt;
        ///    &lt;max hp=&quot;52&quot; atk=&quot;40&quot; skl=&quot;40&quot; spd=&quot;38&quot; lck=&quot;40&quot; def=&quot;42&quot; res=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Characters {
            get {
                return ResourceManager.GetString("Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;class id=&quot;C51B98DC5787885C&quot; name=&quot;Villager (M)&quot;/&gt;
        ///  &lt;class id=&quot;831A98DC2786885C&quot; name=&quot;Villager (F)&quot;/&gt;
        ///  &lt;class id=&quot;4AC058885C6D1EBF&quot; name=&quot;Cavalier (M)&quot;/&gt;
        ///  &lt;class id=&quot;08BF58882C6C1EBF&quot; name=&quot;Cavalier (F)&quot;/&gt;
        ///  &lt;class id=&quot;89A60099B78ACB0C&quot; name=&quot;Paladin (M)&quot;/&gt;
        ///  &lt;class id=&quot;47A500998789CB0C&quot; name=&quot;Paladin (F)&quot;/&gt;
        ///  &lt;class id=&quot;BD41DF7E3385F1C6&quot; name=&quot;Gold Knight (M)&quot;/&gt;
        ///  &lt;class id=&quot;7B40DF7E0384F1C6&quot; name=&quot;Gold Knight (F)&quot;/&gt;
        ///  &lt;class id=&quot;0FFE1B4AA17577 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Classes {
            get {
                return ResourceManager.GetString("Classes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;root&gt;
        ///  &lt;item id=&quot;03&quot; hex=&quot;8AD38FE22E1C0C74&quot;  name=&quot;Iron Sword&quot;&gt;
        ///    &lt;description maxStars=&quot;5&quot; isDLC =&quot;false&quot;/&gt;
        ///  &lt;/item&gt;
        ///  &lt;item id=&quot;04&quot; hex=&quot;25B157CE1DCC106C&quot; name=&quot;Steel Sword&quot;&gt;
        ///    &lt;description maxStars=&quot;5&quot; isDLC =&quot;false&quot;/&gt;
        ///  &lt;/item&gt;
        ///  &lt;item id=&quot;05&quot; hex=&quot;817ADFB445F72C60&quot;  name=&quot;Silver Sword&quot;&gt;
        ///    &lt;description maxStars=&quot;5&quot; isDLC =&quot;false&quot;/&gt;
        ///  &lt;/item&gt;
        ///  &lt;item id=&quot;06&quot; hex=&quot;2018E4D160272E71&quot; name=&quot;Brave Sword&quot;&gt;
        ///    &lt;description maxStars=&quot;3&quot; isDLC =&quot;false&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
    }
}
